sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build  -t matheusmorozetti/ezops-test-matheus-morozetti .

script:
  - docker run -it matheusmorozetti/ezops-test-matheus-morozetti

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ezops-test"
  env: "Ezopstest-env"
  bucket_name: elasticbeanstalk-us-east-2-275810144275
  bucket_path: "ezops-test"
  on:
   branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
