sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build . -t Matheus-Morozetti/ezops-test-matheus-morozetti -f Dockerfile.dev .

script:
  - docker run Matheus-Morozetti/ezops-test-matheus-morozetti