sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build  -t matheusmorozetti/ezops-test-matheus-morozetti -f Dockerfile .

script:
  - docker run matheusmorozetti/ezops-test-matheus-morozetti
