version: '3'
services:
    web:
        environment:
            -CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /home/node/app/node_modules
            - .:/app
        tests:
            build:
                context: .
                dockerfile: Dockerfile.dev
            volumes:
                - /home/node/app/node_modules
                - .:/app
                command: ["npm", "run", "test"]