version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /node_modules
      - .:/usr/src/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/app/
      - .:/
    command: ["npm", "run", "test"]